### ISSUE TITLE
Need ability to restore factory firmware

### ISSUE THREAD

**Issue by gutschke** [LIST-LUXEMBOURG/KniwwelinoLib#4]
I followed the instructions on the official Kniwwelino website and the instructions on this Github page to try to upload a sketch. The instructions vary slightly and suggest using different board types. In the process, I ended up wiping the factory firmware, and I currently am unable to use any of the hardware (it accepts new sketches from the Arduino IDE, but other than that, I can get any of the LEDs to do anything).

I suspect I need to reflash the original factory firmware to get back to a known good state. But I can't find any link to download the software nor instructions how to install it. Preferably, I'd need this to be suitable for Linux, but I can find a Windows machine too.

**Comment by lazyzero** [comment]
Hello @gutschke,

we have a beta of an adapted version of flasher.js to restore the factory firmware of Kniwwelino. oyu can download and test it from:

- https://doku.kniwwelino.lu/_media/stuff/flasher.js_1.1.0_amd64.deb
- https://doku.kniwwelino.lu/_media/stuff/flasher.js-setup-win32-x64.exe

Your feedback is appreciated. 
To program it with Arduino I suggest to use the esp8266 core in version 2.4.0, I will update the documentation on https://doku.kniwwelino.lu

Sorry for any inconvenience
Christian

**Comment by lazyzero** [comment]
@step-team-jf you can close this issue

**Comment by gutschke** [comment]
I couldn't get the Linux binary to work. It doesn't appear to be able to find any USB devices. I checked with strace, it does all sorts of things to enumerate USB devices, but for some reason it doesn't like any of the ones that it finds.

On a whim, I tried explicitly passing /dev/ttyUSB0 on the command line to flasher.js. But that still didn't make any difference. But /dev/ttyUSB0 would definitely have been the correct device and my user does have permission to access this serial device.

I then tried the Windows binary in a virtual machine. Took some fiddling around until the serial port was visible in the VM, but once it did, flasher.js was able to revive my Kniwwelino. So, things aren't quite user-friendly yet (but you did warn about that); with enough effort, things work though.

Maybe, for Linux you could document where to download the firmware image and provide a standard command line tool (is there something that is already part of the Arduino IDE maybe?) to upload firmware? Linux users are frequently happy to forgo the UI, if there are simple command line tools. Just a suggestion...

Thank you for helping me so fast.

**Comment by lazyzero** [comment]
If I understand correctly the code of flasher.js you must be member of the group dialout to make it work. That is how I use it on Kubuntu 18.04

For manual download, the current firmware is described in https://code.kniwwelino.lu/flasher/v1.10.0/manifest.json There you can see where to download the bin files and at which addresses you have to flash them. If you have Arduino with the esp core you will find a tool called espflash in ~/.arduino15/packages/esp8266/tools/esptool/

Best Christian

**Comment by gutschke** [comment]
I wrote a quick bash script that should allow anybody to reset a Kniwwelino to factory firmware. It requires a relatively recent version of "bash" and a couple of extra Linux tools. But there is nothing that wouldn't be available in a standard Linux distribution:

[reset_kniwwelino.sh.gz](https://github.com/LIST-LUXEMBOURG/KniwwelinoLib/files/2395028/reset_kniwwelino.sh.gz)

Would you mind publishing the script somewhere on your site. I'd be happy to assign copyright or to put it under whatever type of license works for you.

**Comment by gutschke** [comment]
Awesome. Here is the GIT repository:
https://github.com/gutschke/reset_kniwwelino

BTW, is there a way to automatically find the most recent public JSON
Manifest? Or is it better if this URL is always hard-coded in my script?


Markus

**Comment by lazyzero** [comment]
Hi Markus,
I will add your repository on the download page of our Wiki. 
The list of restore files can be found in the base manifest https://code.kniwwelino.lu/flasher/manifest.json
Latest version has a flag. Okay, there is only one for the moment ;-)

Christian
