### ISSUE TITLE
Unable to connect to AP with long WiFi SSID/Password

### ISSUE THREAD

**Issue by S7701** [LIST-LUXEMBOURG/KniwwelinoLib#6]
Connections to APs with long SSI or password fail because the arrays for the SSID and password that are passed to WiFi.begin() in KniwwelinoLib::WIFIsetup() are limited to 20 characters.

**Comment by lazyzero** [comment]
Hello S7701,
yes that is correct. We didn't assume there are many people really using long SSID. Indeed you are the first one reporting this issue. By definition the max length of SSID could be 32 and for WPA2 paswords its 8-63 characters.

We will discuss if we will change this.

**Comment by lazyzero** [comment]
The issue should be fixed with release 1.2.0 of the lib

@S7701 please confirm if it works now.

**Comment by S7701** [comment]
Seems to work. Thank you

**Comment by lazyzero** [comment]
This repository was moved to https://github.com/kniwwelino/KniwwelinoLib/
